FROM zefciu/python-base
MAINTAINER Pylabs <pylabs@allegro.pl>
RUN pip install nose py3dns requests flake8
RUN mkdir dnsaas-source
ADD setup.py dnsaas-source/setup.py
ADD Makefile dnsaas-source/Makefile
ADD README.rst dnsaas-source/README.rst
ADD version.json dnsaas-source/version.json
ADD requirements/base.txt dnsaas-source/requirements/base.txt
ADD requirements/dev.txt dnsaas-source/requirements/dev.txt
ADD powerdns dnsaas-source/powerdns
ADD dnsaas dnsaas-source/dnsaas
ADD ui dnsaas-source/ui
RUN cd dnsaas-source && pip install -e .
ADD integration-tests integration-tests
CMD /bin/sh integration-tests/runtests.sh
